# Mosaics Notebook

In [1]:
def polygon_enumeration(n, m):
    if m <= 1: return 0
    elif m == 2:
        M = matrix(QQ, 
            [
                [1,1],
                [1,1],
            ]
        )
    elif m >= 3:
        M = matrix(QQ, 
            [
                [1,1,1,1],
                [1,1,0,1],
                [1,0,1,1],
                [1,1,1,1],
            ]
        )

        for _ in range(m-3):
            row_nums = M.nrows()
            half_row_nums = row_nums//2
            col_nums = M.ncols()
            half_col_nums = col_nums//2

            M_1 = matrix([[M[i][j] for j in range(half_col_nums)] for i in range(half_row_nums)])
            M_2 = matrix([[M[i][j] for j in range(half_col_nums, col_nums)] for i in range(half_row_nums)])
            M_3 = matrix([[M[i][j] for j in range(half_col_nums)] for i in range(half_row_nums, row_nums)])
            M_4 = matrix([[M[i][j] for j in range(half_col_nums, col_nums)] for i in range(half_row_nums, row_nums)])

            M = block_matrix(
                [
                    [M_1, M_2, M_1, M_2],
                    [M_3, M_4, 0*M_3, M_4],
                    [M_1, 0*M_2, M_1, M_2],
                    [M_3, M_4, M_3, M_4]
                ]
            )

    val = (M[0] * M**(n-2) * M[:,0])[0]
    return val

def messy_polygon_enumeration(n, m, b=7):
    if m <= 1: return 0
    # define matrix  M
    elif m == 2:
        M = matrix(QQ, 
            [
                [b**2,1],
                [-1,1],
            ]
        )
    
    elif m >= 3:
        M = matrix(QQ, 
            [
                [b**3,b,b,1],
                [-b,b,0,1],
                [-b,0,b,1],
                [-1,1,1,b],
            ]
        )

        for _ in range(m-3):

            row_nums = M.nrows()
            half_row_nums = row_nums//2
            col_nums = M.ncols()
            half_col_nums = col_nums//2

            M_1 = matrix([[M[i][j] for j in range(half_col_nums)] for i in range(half_row_nums)])
            M_2 = matrix([[M[i][j] for j in range(half_col_nums, col_nums)] for i in range(half_row_nums)])
            M_3 = matrix([[M[i][j] for j in range(half_col_nums)] for i in range(half_row_nums, row_nums)])
            M_4 = matrix([[M[i][j] for j in range(half_col_nums, col_nums)] for i in range(half_row_nums, row_nums)])

            M = block_matrix(
                [
                    [b*M_1, b*M_2, M_1/b, M_2],
                    [b*M_3, b*M_4, 0*M_3, M_4],
                    [-1*M_1/b, 0*M_2, M_1/b, M_2],
                    [M_3, M_4, -1*M_3, b*M_4]
                ]
            )

    print(f'A({m}) = ')
    print(M)

    val = (M[0] * M**(n-2) * M[:,0])[0]
    return val

for n in range(2, 7):
    m = n
    # val = polygon_enumeration(n=n, m=m)
    # print(f't_{n},{m} = {val}')
    val = messy_polygon_enumeration(n=n, m=m, b=6)
    # print(f't_({n},{m}) = {val}')
    # print(f'6^({n}*{m}) - t_({n},{m}) = {6**(n*m) - val}')
    # print(f'p_({n},{m}) = {(val / 6**(n*m)).n()}')


A(2) = 
[36  1]
[-1  1]
A(3) = 
[216   6   6   1]
[ -6   6   0   1]
[ -6   0   6   1]
[ -1   1   1   6]
A(4) = 
[1296   36|  36    6|  36    1|   6    1]
[ -36   36|   0    6|  -1    1|   0    1]
[---------+---------+---------+---------]
[ -36    0|  36    6|   0    0|   6    1]
[  -6    6|   6   36|   0    0|   1    6]
[---------+---------+---------+---------]
[ -36   -1|   0    0|  36    1|   6    1]
[   1   -1|   0    0|  -1    1|   0    1]
[---------+---------+---------+---------]
[  -6    0|   6    1|   6    0|  36    6]
[  -1    1|   1    6|   1   -1|   6   36]
A(5) = 
[7776  216  216   36| 216    6   36    6| 216    6    6    1|  36    1    6    1]
[-216  216    0   36|  -6    6    0    6|  -6    6    0    1|  -1    1    0    1]
[-216    0  216   36|   0    0   36    6|  -6    0    6    1|   0    0    6    1]
[ -36   36   36  216|   0    0    6   36|  -1    1    1    6|   0    0    1    6]
[-------------------+-------------------+-------------------+-------------------]
[-216   

In [ ]:
def a(n):
    if n < 2: return 0 # check that the solution you eventually find for a,b,c,d includes this 
    if n == 2: return 36
    return 6 * a(n-1) + 6 * b(n-1)


def b(n):
    if n < 2: return 0
    if n == 2: return 0
    return 6 * b(n-1) + 6 * d(n-1)


def c(n):
    if n < 2: return 0
    if n == 2: return 0
    return 6 * c(n-1) + 6 * b(n-1)

def d(n):
    if n < 2: return 0
    if n == 2: return 1
    return 6 * d(n-1) + (1/3) * b(n-1)

def f(n):
    return 2*a(n) + 4 * b(n) + 2*c(n) + d(n)

def T_3(n):
    if n < 2: return 0
    if n == 2: return 73
    sum = 0
    for i in range(2,n-1):
        sum += (6**(3*(n-i)) - T_3(n-i)) * (2*a(i)+4*b(i)+2*c(i)+d(i))
    return 216*T_3(n-1) + sum + 216*(2*a(n-1)+4*b(n-1)+2*c(n-1)+d(n-1)) + (2*a(n)+4*b(n)+2*c(n)+d(n))

In [1]:
import numpy as np

def L_2(w):
    b = (36**(w-2))*np.array([[1],[1]])
    # b = np.array([[1],[1]])
    m = np.array(
        [
            [36, 1],
            [-1, 1]
        ]
    )
    if w == 2: return b
    return np.dot(m, L_2(w-1)) + b

def L_3(w):
    b = (216**(w-2))*np.array([[73],[37], [37], [18]])
    # b = np.array([[1],[1]])
    m = np.array(
        [
            [216, 6, 6, 1],
            [-6, 6, 0, 1],
            [-6, 0, 6, 1],
            [-1, 1, 1, 6]
        ]
    )
    if w == 2: return b
    return np.dot(m, L_3(w-1)) + b

for w in range(2,8):
    print(f'L_2({w}) = {L_2(w)}')
    # print(f'L_3({w}) = {L_3(w)}')


L_2(2) = [[1]
 [1]]
L_2(3) = [[73]
 [36]]
L_2(4) = [[3960]
 [1259]]
L_2(5) = [[190475]
 [ 43955]]
L_2(6) = [[8580671]
 [1533096]]
L_2(7) = [[370903428]
 [ 53418601]]


In [3]:

def t(n):
    if n <= 1: return 0
    elif n == 2: return 1
    elif n > 2:
        val = 36*t(n-1)
        for i in range(2,n+1):
            val += (6**(2*(n-i)) - t(n-i))
        return val

for n in range(2,8):
    print(f't({n}) = {t(n)}')


t(2) = 1
t(3) = 73
t(4) = 3960
t(5) = 190475
t(6) = 8580671
t(7) = 370903428


In [3]:
# TODO main diagonal

main_diag = [1, 31998, 20334816290, 365320963733070828]

for i in range(len(main_diag)-2):
    print(f'{(main_diag[i+2]*main_diag[i]/(main_diag[i+1]**2))**(1/2)}')


4.456534701235387
5.316899619688655


In [20]:
# make A matrix for specific weights 
def make_A_from_weights(weights: dict):
    A = matrix(QQ, 
        [
            [weights[1]*weights[1],weights[2]*weights[5]],
            [weights[3]*weights[9],weights[4]*weights[13]],
        ]
    )

    return A

# make V matrix for specific weights 
def make_V_from_weights(weights: dict):
    V = matrix(QQ, 
        [
            [weights[1],weights[2]*weights[5]/weights[1],weights[1],weights[6]],
            [weights[3]*weights[9]/weights[1],weights[4]*weights[13]/weights[1],weights[3]*weights[10]/weights[2],weights[4]*weights[14]/weights[2]],
            [weights[1],weights[2]*weights[7]/weights[3],weights[1],weights[2]*weights[8]/weights[4]],
            [weights[11],weights[4]*weights[15]/weights[3],weights[3]*weights[12]/weights[4],weights[16]],
        ]
    )

    return V

# make larger A using V
def make_new_A(A, V):
    row_nums = A.nrows()
    half_row_nums = row_nums//2
    col_nums = A.ncols()
    half_col_nums = col_nums//2
    # read A as block matrix
    A_00 = matrix([[A[i][j] for j in range(half_col_nums)] for i in range(half_row_nums)])
    A_01 = matrix([[A[i][j] for j in range(half_col_nums, col_nums)] for i in range(half_row_nums)])
    A_10 = matrix([[A[i][j] for j in range(half_col_nums)] for i in range(half_row_nums, row_nums)])
    A_11 = matrix([[A[i][j] for j in range(half_col_nums, col_nums)] for i in range(half_row_nums, row_nums)])
    # construct new A
    A = block_matrix(
        [
            [V[0][0]*A_00, V[0][1]*A_00, V[0][2]*A_01, V[0][3]*A_01],
            [V[1][0]*A_00, V[1][1]*A_00, V[1][2]*A_01, V[1][3]*A_01],
            [V[2][0]*A_10, V[2][1]*A_10, V[2][2]*A_11, V[2][3]*A_11],
            [V[3][0]*A_10, V[3][1]*A_10, V[3][2]*A_11, V[3][3]*A_11]
        ]
    )
    return A

# general mosaic enumeration 
def messy_polygon_mosaic_enumeration(weights:dict, n: int, m: int):
    if m <= 1: return weights[1]**(n*m)
    # define starter 2x2 matrix A
    A = make_A_from_weights(weights=weights)
    # define coefficient matrix V
    V = make_V_from_weights(weights=weights)

    # recursively construct A(m)
    for _ in range(m-2):
        A = make_new_A(A=A, V=V)
        # print(f'{_} :: {max(A.eigenvalues())/11**(_+3)}')

    return (A**(n))[0][0]

In [23]:
from time import time

# ground_truth_3x3 = 11+(4*11)+(4*(11**3))+(4*(11**5))+(2*4*(11**2))
# print(f'Ground truth for 3x3: {ground_truth_3x3}\n')

weights = {1: 11, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: -4, 8: 1, 9: -1, 10: 4, 11: 1, 12: 1, 13: 1, 14: 1, 15: -1, 16: 11}
# main diaganol
for n in range(1,11):
    start = time()
    num_non_polygon_mosaics = messy_polygon_mosaic_enumeration(weights = weights, n = n, m = n)
    prob = (1 - num_non_polygon_mosaics/weights[1]**(n*n)).n()
    print(f'Probability of a polygon mosaics in {n} by {n} grid: {prob:.6f}. Completed in {time()-start:.4f}s')
    # print(11**(n*n) - num_non_polygon_mosaics)


Probability of a polygon mosaics in 1 by 1 grid: 0.000000. Completed in 0.0001s
Probability of a polygon mosaics in 2 by 2 grid: 0.000068. Completed in 0.0002s
Probability of a polygon mosaics in 3 by 3 grid: 0.000276. Completed in 0.0003s
Probability of a polygon mosaics in 4 by 4 grid: 0.000623. Completed in 0.0005s
Probability of a polygon mosaics in 5 by 5 grid: 0.001110. Completed in 0.0009s
Probability of a polygon mosaics in 6 by 6 grid: 0.001737. Completed in 0.0026s
Probability of a polygon mosaics in 7 by 7 grid: 0.002502. Completed in 0.0144s
Probability of a polygon mosaics in 8 by 8 grid: 0.003407. Completed in 0.0768s
Probability of a polygon mosaics in 9 by 9 grid: 0.004450. Completed in 0.6316s
Probability of a polygon mosaics in 10 by 10 grid: 0.005631. Completed in 4.4569s


In [22]:
# 6 tiles weights
weights = {1: 6, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 0, 8: 1, 9: -1, 10: 0, 11: 1, 12: 1, 13: 1, 14: 1, 15: -1, 16: 6}
for n in range(1,11):
    start = time()
    num_non_polygon_mosaics = messy_polygon_mosaic_enumeration(weights = weights, n = n, m = n)
    prob = (1 - num_non_polygon_mosaics/weights[1]**(n*n)).n()
    print(f'Probability of a polygon mosaics in {n} by {n} grid: {prob:.6f}. Completed in {time()-start:.4f}s')
    # print(11**(n*n) - num_non_polygon_mosaics)


Probability of a polygon mosaics in 1 by 1 grid: 0.000000. Completed in 0.0001s
Probability of a polygon mosaics in 2 by 2 grid: 0.000772. Completed in 0.0002s
Probability of a polygon mosaics in 3 by 3 grid: 0.003175. Completed in 0.0003s
Probability of a polygon mosaics in 4 by 4 grid: 0.007208. Completed in 0.0005s
Probability of a polygon mosaics in 5 by 5 grid: 0.012853. Completed in 0.0009s
Probability of a polygon mosaics in 6 by 6 grid: 0.020086. Completed in 0.0028s
Probability of a polygon mosaics in 7 by 7 grid: 0.028874. Completed in 0.0125s
Probability of a polygon mosaics in 8 by 8 grid: 0.039179. Completed in 0.0637s
Probability of a polygon mosaics in 9 by 9 grid: 0.050953. Completed in 0.5054s
Probability of a polygon mosaics in 10 by 10 grid: 0.064145. Completed in 3.5285s


In [13]:
from weights import get_solutions

solution_set = get_solutions()

unique_As = []
unique_Vs = []

for sol_num, sol in enumerate(solution_set):
    sol_string = f'{sol_num+1} :: {sol}'
    # for num in sol:
    #     thing += str(num) + ' & '
    # thing += ' \\\\'
    # print(sol_string)

    # print(f'[w_1 ... w_16] & = & {[6] +sol[1:-1] + [6]} \\\\')

    A = make_A_from_weights(weights=[0]+sol)
    if A not in unique_As: unique_As.append(A)
    V = make_V_from_weights(weights=[0]+sol)
    if V not in unique_Vs: unique_Vs.append(V)

# print(len(solution_set))
# print(len(unique_As))
# print(len(unique_Vs))

for A_mat in unique_As:
    print(A_mat)
    print()


for V_mat in unique_Vs:
    print(V_mat)
    print()




[ 1 -1]
[ 1  1]

[ 1  1]
[-1  1]

[-1  1 -1 -1]
[-1 -1  1  1]
[-1 -1 -1 -1]
[-1 -1 -1 -1]

[-1  1 -1  1]
[-1 -1  1 -1]
[-1 -1 -1  1]
[ 1  1  1 -1]

[-1 -1 -1 -1]
[ 1 -1 -1 -1]
[-1  1 -1 -1]
[-1  1 -1 -1]

[-1 -1 -1  1]
[ 1 -1 -1  1]
[-1  1 -1  1]
[ 1 -1  1 -1]

[ 1 -1  1 -1]
[ 1  1 -1  1]
[ 1  1  1 -1]
[-1 -1 -1  1]

[ 1 -1  1  1]
[ 1  1 -1 -1]
[ 1  1  1  1]
[ 1  1  1  1]

[ 1  1  1 -1]
[-1  1  1 -1]
[ 1 -1  1 -1]
[-1  1 -1  1]

[ 1  1  1  1]
[-1  1  1  1]
[ 1 -1  1  1]
[ 1 -1  1  1]

